Repository open-mmlab/mmselfsup, pull requests merged in 2022-08, with the labels that each got.

#390 [Docs]: Add comments of barlowtwins linear evaluation setting.
  configs/benchmarks/classification/imagenet/resnet50_linear-8xb32-coslr-100e_in1k.py
Labels: dev-1.x

#375 [Refactor]: Refactor layer wise lr decay
  mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py
  tests/test_engine/test_optimizers/test_layer_decay_optim_wrapper_constructor.py
Labels: dev-1.x

#399 [Refactor] Refactor benchmark config files
  configs/benchmarks/mmdetection/_base_/datasets/coco_instance.py
  configs/benchmarks/mmdetection/_base_/datasets/voc0712.py
  configs/benchmarks/mmdetection/_base_/default_runtime.py
  configs/benchmarks/mmdetection/_base_/models/faster_rcnn_r50_c4.py
  configs/benchmarks/mmdetection/_base_/models/mask_rcnn_r50_c4.py
  configs/benchmarks/mmdetection/_base_/models/mask_rcnn_r50_fpn.py
  configs/benchmarks/mmdetection/_base_/schedules/schedule_1x.py
  configs/benchmarks/mmdetection/_base_/schedules/schedule_24k.py
  configs/benchmarks/mmdetection/_base_/schedules/schedule_2x.py
  configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py
  configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_2x_coco.py
  configs/benchmarks/mmdetection/coco/mask_rcnn_r50_fpn_mstrain_1x_coco.py
  configs/benchmarks/mmdetection/coco/mask_rcnn_r50_fpn_mstrain_2x_coco.py
  configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_24k_voc0712.py
  configs/benchmarks/mmsegmentation/_base_/datasets/cityscapes.py
  configs/benchmarks/mmsegmentation/_base_/datasets/cityscapes_769x769.py
  configs/benchmarks/mmsegmentation/_base_/datasets/pascal_voc12.py
  configs/benchmarks/mmsegmentation/_base_/datasets/pascal_voc12_aug.py
  configs/benchmarks/mmsegmentation/_base_/default_runtime.py
  configs/benchmarks/mmsegmentation/_base_/models/fcn_r50-d8.py
  configs/benchmarks/mmsegmentation/_base_/schedules/schedule_20k.py
  configs/benchmarks/mmsegmentation/_base_/schedules/schedule_40k.py
  configs/benchmarks/mmsegmentation/cityscapes/fcn_r50-d8_769x769_40k_cityscapes.py
  configs/benchmarks/mmsegmentation/voc12aug/fcn_r50-d8_512x512_20k_voc12aug.py
  tools/benchmarks/mmdetection/mim_dist_train_c4.sh
  tools/benchmarks/mmdetection/mim_dist_train_fpn.sh
  tools/benchmarks/mmdetection/mim_slurm_train_c4.sh
  tools/benchmarks/mmdetection/mim_slurm_train_fpn.sh
  tools/benchmarks/mmsegmentation/mim_dist_train.sh
  tools/benchmarks/mmsegmentation/mim_slurm_train.sh
Labels: dev-1.x

#392 [Refactor]: Rename SelfSupLocalVisualizer to SelfSupVisualizer
  configs/selfsup/_base_/default_runtime.py
  docs/en/tutorials/0_config.md
  mmselfsup/visualization/__init__.py
  mmselfsup/visualization/selfsup_visualizer.py
  tests/test_visualization/test_visualizer.py
Labels: dev-1.x

#419 [Refactor] Refactor docs directory
  docs/en/advanced_guides/add_datasets.md
  docs/en/advanced_guides/add_modules.md
  docs/en/advanced_guides/add_transforms.md
  docs/en/advanced_guides/conventions.md
  docs/en/advanced_guides/customize_runtime.md
  docs/en/advanced_guides/data_flow.md
  docs/en/advanced_guides/datasets.md
  docs/en/advanced_guides/engine.md
  docs/en/advanced_guides/evaluation.md
  docs/en/advanced_guides/index.rst
  docs/en/advanced_guides/models.md
  docs/en/advanced_guides/structures.md
  docs/en/advanced_guides/transforms.md
  docs/en/algorithms/barlowtwins.md
  docs/en/algorithms/byol.md
  docs/en/algorithms/cae.md
  docs/en/algorithms/deep.md
  docs/en/algorithms/dense.md
  docs/en/algorithms/mae.md
  docs/en/algorithms/moco.md
  docs/en/algorithms/mocov3.md
  docs/en/algorithms/npid.md
  docs/en/algorithms/odc.md
  docs/en/algorithms/rl.md
  docs/en/algorithms/rp.md
  docs/en/algorithms/simclr.md
  docs/en/algorithms/simmim.md
  docs/en/algorithms/ss.md
  docs/en/algorithms/swav.md
  docs/en/api.rst
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/install.md
  docs/en/migration.md
  docs/en/model_zoo.md
  docs/en/notes/changelog.md
  docs/en/notes/contribution_guides.md
  docs/en/notes/faq.md
  docs/en/overview.md
  docs/en/tutorials/4_schedule.md
  docs/en/user_guides/1_config.md
  docs/en/user_guides/2_dataset_prepare.md
  docs/en/user_guides/3_pretrain.md
  docs/en/user_guides/analysis_tools.md
  docs/en/user_guides/classification.md
  docs/en/user_guides/detection.md
  docs/en/user_guides/index.rst
  docs/en/user_guides/segmentation.md
  docs/en/user_guides/visualization.md
Labels: dev-1.x

#414 [Feature]: Add missing docstring for dataset
  mmselfsup/datasets/deepcluster_dataset.py
  mmselfsup/datasets/samplers/deepcluster_sampler.py
  mmselfsup/datasets/transforms/formatting.py
  mmselfsup/datasets/transforms/processing.py
  mmselfsup/datasets/transforms/wrappers.py
Labels: dev-1.x

#428 [Refactor] Update import dependency
  mmselfsup/models/backbones/cae_vit.py
  mmselfsup/models/backbones/simmim_swin.py
  mmselfsup/models/necks/cae_neck.py
  mmselfsup/models/utils/transformer_blocks.py
Labels: dev-1.x

#417 [Fix]: fix docstring of visualization
  mmselfsup/structures/selfsup_data_sample.py
  mmselfsup/visualization/selfsup_visualizer.py
Labels: dev-1.x

#424 [Feature] Add benchmark scripts
  .dev_scripts/benchmark_regression/models.yml
  .dev_scripts/benchmark_regression/pretrain_with_cls.py
  configs/selfsup/mocov3/metafile.yml
Labels: dev-1.x

#423 [Refactor] Rename config files, change `fp16` to `amp`
  configs/selfsup/byol/byol_resnet50_8xb256-amp-accum2-coslr-100e_in1k.py
  configs/selfsup/byol/byol_resnet50_8xb256-amp-accum2-coslr-200e_in1k.py
  configs/selfsup/byol/byol_resnet50_8xb256-amp-accum2-coslr-300e_in1k.py
  configs/selfsup/cae/cae_vit-base-p16_16xb128-amp-coslr-300e_in1k.py
  configs/selfsup/cae/cae_vit-base-p16_32xb64-amp-coslr-300e_in1k.py
  configs/selfsup/cae/cae_vit-base-p16_8xb256-amp-coslr-300e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-1600e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-300e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-400e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-800e_in1k.py
  configs/selfsup/mocov3/mocov3_vit-small-p16_16xb256-amp-coslr-300e_in1k.py
  configs/selfsup/rotation_pred/rotation-pred_resnet50_8xb16-amp-steplr-70e_in1k.py
  configs/selfsup/simmim/simmim_swin-base_16xb128-amp-coslr-100e_in1k-192.py
  configs/selfsup/simmim/simmim_swin-base_8xb256-amp-coslr-100e_in1k-192.py
Labels: dev-1.x

#427 [Fix] update pip requirement
  requirements/readthedocs.txt
  requirements/runtime.txt
Labels: dev-1.x

#422 [Fix] Fix ut
  tests/test_engine/test_hooks/test_densecl_hook.py
  tests/test_engine/test_hooks/test_simsiam_hook.py
  tests/test_engine/test_hooks/test_swav_hook.py
  tests/test_models/test_algorithms/test_barlowtwins.py
  tests/test_models/test_algorithms/test_byol.py
  tests/test_models/test_algorithms/test_cae.py
  tests/test_models/test_algorithms/test_deepcluster.py
  tests/test_models/test_algorithms/test_densecl.py
  tests/test_models/test_algorithms/test_mae.py
  tests/test_models/test_algorithms/test_moco.py
  tests/test_models/test_algorithms/test_mocov3.py
  tests/test_models/test_algorithms/test_npid.py
  tests/test_models/test_algorithms/test_odc.py
  tests/test_models/test_algorithms/test_relative_loc.py
  tests/test_models/test_algorithms/test_rotation_pred.py
  tests/test_models/test_algorithms/test_simclr.py
  tests/test_models/test_algorithms/test_simmim.py
  tests/test_models/test_algorithms/test_simsiam.py
  tests/test_models/test_algorithms/test_swav.py
Labels: dev-1.x

#432 [Refactor] refine docstring for algorithms and memories
  mmselfsup/models/algorithms/barlowtwins.py
  mmselfsup/models/algorithms/base.py
  mmselfsup/models/algorithms/byol.py
  mmselfsup/models/algorithms/cae.py
  mmselfsup/models/algorithms/deepcluster.py
  mmselfsup/models/algorithms/densecl.py
  mmselfsup/models/algorithms/mae.py
  mmselfsup/models/algorithms/moco.py
  mmselfsup/models/algorithms/mocov3.py
  mmselfsup/models/algorithms/npid.py
  mmselfsup/models/algorithms/odc.py
  mmselfsup/models/algorithms/relative_loc.py
  mmselfsup/models/algorithms/rotation_pred.py
  mmselfsup/models/algorithms/simclr.py
  mmselfsup/models/algorithms/simmim.py
  mmselfsup/models/algorithms/simsiam.py
  mmselfsup/models/algorithms/swav.py
  mmselfsup/models/memories/odc_memory.py
  mmselfsup/models/memories/simple_memory.py
Labels: dev-1.x

#426 [Refactor] Modify documents of classification, detection and segmentation
  docs/en/user_guides/classification.md
  docs/en/user_guides/detection.md
  docs/en/user_guides/segmentation.md
  tools/benchmarks/classification/mim_dist_test.sh
  tools/benchmarks/classification/mim_slurm_test.sh
  tools/benchmarks/mmdetection/mim_dist_test.sh
  tools/benchmarks/mmdetection/mim_slurm_test.sh
  tools/benchmarks/mmsegmentation/mim_dist_test.sh
  tools/benchmarks/mmsegmentation/mim_slurm_test.sh
Labels: dev-1.x

#434 [Docs] refactor dataset_prepare.md
  docs/en/user_guides/2_dataset_prepare.md
  tools/dataset_converters/prepare_voc07_cls.sh
Labels: dev-1.x

#458 [Fix] fix index bug
  docs/en/index.rst
Labels: dev-1.x

#459 [Docs] refactor 3_pretrain.md
  docs/en/user_guides/3_pretrain.md
Labels: Documentation, dev-1.x

#420 [Refactor] refactor knn
  configs/benchmarks/classification/knn_imagenet.py
  tools/benchmarks/classification/knn_imagenet/dist_test_knn_epoch.sh
  tools/benchmarks/classification/knn_imagenet/dist_test_knn_pretrain.sh
  tools/benchmarks/classification/knn_imagenet/slurm_test_knn_epoch.sh
  tools/benchmarks/classification/knn_imagenet/slurm_test_knn_pretrain.sh
  tools/benchmarks/classification/knn_imagenet/test_knn.py
Labels: dev-1.x

#415 [Refactor] Refine models docstring
  mmselfsup/models/backbones/cae_vit.py
  mmselfsup/models/backbones/mae_vit.py
  mmselfsup/models/backbones/mocov3_vit.py
  mmselfsup/models/backbones/resnet.py
  mmselfsup/models/backbones/resnext.py
  mmselfsup/models/backbones/simmim_swin.py
  mmselfsup/models/heads/cae_head.py
  mmselfsup/models/heads/cls_head.py
  mmselfsup/models/heads/latent_heads.py
  mmselfsup/models/heads/multi_cls_head.py
  mmselfsup/models/necks/densecl_neck.py
  mmselfsup/models/necks/linear_neck.py
  mmselfsup/models/necks/mae_neck.py
  mmselfsup/models/necks/mocov2_neck.py
  mmselfsup/models/necks/nonlinear_neck.py
  mmselfsup/models/necks/odc_neck.py
  mmselfsup/models/necks/relative_loc_neck.py
  mmselfsup/models/necks/swav_neck.py
Labels: dev-1.x

#438 [Feature]: Add structure docs
  docs/en/advanced_guides/structures.md
Labels: Documentation, dev-1.x

#439 [Feature]: Add data flow doc
  docs/en/advanced_guides/data_flow.md
Labels: Documentation, dev-1.x

#453 [Docs] add faq contributing
  docs/en/notes/contribution_guide.md
  docs/en/notes/contribution_guides.md
  docs/en/notes/faq.md
Labels: Documentation, dev-1.x

#449 [Docs] refactor config.md
  docs/en/user_guides/1_config.md
Labels: Documentation, dev-1.x

#448 [Docs]: Add user_guides/analysis_tools.md
  docs/en/user_guides/analysis_tools.md
Labels: Documentation, dev-1.x

#430 [Fix]: Fix some bugs related to MAE and CAE
  configs/benchmarks/classification/imagenet/vit-base-p16_ft-8xb128-coslr-100e-rpe_in1k.py
  configs/benchmarks/classification/imagenet/vit-base-p16_ft-8xb128-coslr-100e_in1k.py
  configs/benchmarks/classification/imagenet/vit-base-p16_linear-8xb2048-coslr-90e_in1k.py
  configs/benchmarks/classification/imagenet/vit-base-p16_linear-8xb512-coslr-sgd-90e_in1k.py
  configs/benchmarks/classification/imagenet/vit-huge-p16_ft-32xb8-coslr-50e_in1k-448.py
  configs/benchmarks/classification/imagenet/vit-huge-p16_ft-8xb128-coslr-50e_in1k.py
  configs/benchmarks/classification/imagenet/vit-large-p16_ft-8xb128-coslr-50e_in1k.py
  configs/benchmarks/classification/imagenet/vit-large-p16_linear-8xb2048-coslr-90e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-1600e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-300e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-800e_in1k.py
  configs/selfsup/mae/mae_vit-base-p16_8xb512-coslr-400e_in1k.py
  configs/selfsup/mae/mae_vit-huge-p16_8xb512-amp-coslr-1600e_in1k.py
  configs/selfsup/mae/mae_vit-large-p16_8xb512-amp-coslr-1600e_in1k.py
  configs/selfsup/mae/mae_vit-large-p16_8xb512-amp-coslr-300e_in1k.py
  configs/selfsup/mae/mae_vit-large-p16_8xb512-amp-coslr-400e_in1k.py
  configs/selfsup/mae/mae_vit-large-p16_8xb512-amp-coslr-800e_in1k.py
  mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py
  mmselfsup/models/backbones/mae_vit.py
  mmselfsup/models/necks/__init__.py
  mmselfsup/models/necks/mae_neck.py
Labels: dev-1.x

#440 [Docs] Add customize_runtime.md
  docs/en/advanced_guides/customize_runtime.md
Labels: Documentation, dev-1.x

#457 [Docs] refactor get_started.md
  docs/en/get_started.md
Labels: Documentation, dev-1.x

#436 [Docs] Refine add-datasets and add-transform docs
  docs/en/advanced_guides/add_datasets.md
  docs/en/advanced_guides/add_transforms.md
Labels: Documentation, dev-1.x

#433 [Docs] add migration
  docs/en/migration.md
Labels: Documentation, dev-1.x

#447 [Docs] refactor model zoo
  docs/en/model_zoo.md
Labels: Documentation, dev-1.x

#455 [Docs]: Add user_guides/visualization.md
  docs/en/user_guides/visualization.md
Labels: Documentation, dev-1.x

#464 Bump version to v1.0.0rc0
  README.md
  README_zh-CN.md
  docker/Dockerfile
  docs/en/advanced_guides/data_flow.md
  docs/en/get_started.md
  docs/en/notes/changelog.md
  docs/en/notes/faq.md
  docs/en/overview.md
  mmselfsup/__init__.py
  mmselfsup/models/algorithms/odc.py
  requirements/docs.txt
  requirements/mminstall.txt
  requirements/readthedocs.txt
  requirements/runtime.txt
Labels: WIP
